# Generated by Django 6.1.1 on 2026-09-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_folder_event_folder'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_event_attendee',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='session_type',
            field=models.CharField(choices=[('1', 'Time In Only'), ('2', 'Time In & Time Out'), ('3', 'Two-Part (Time In 1, Time Out 1, Time In 2, Time Out 2)')], default='1', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('event', 'email'), name='unique_event_email'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('student_id__isnull', False), models.Q(('student_id', ''), _negated=True)), fields=('event', 'student_id'), name='unique_event_student_id'),
        ),
    ]
