# Generated by Django 6.1.1 on 2026-09-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_attendancerecord_unique_event_attendee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end_time_1',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start_time_1',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.TextField(default='admin', max_length=20),
            preserve_default=False,
        ),
    ]
