# Generated by Django 6.1.1 on 2026-10-10 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_officer_multiple_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_attendance_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
